services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=neondb_owner
      - POSTGRES_PASSWORD=npg_G9CBKQaPmYH5
      - POSTGRES_DB=ep-summer-flower-a1jqprae
    ports:
      - "5432:5432"
    volumes:
      - ./storages/postgres:/var/lib/postgresql/data

  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: "on-failure"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - src/.env
    environment:
      - DB_URI=postgresql://neondb_owner:npg_G9CBKQaPmYH5@ep-summer-flower-a1jqprae-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - DB_KEYS_URI=postgresql://neondb_owner:npg_G9CBKQaPmYH5@ep-summer-flower-a1jqprae-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  sqlite_web:
    image: coleifer/sqlite-web:latest
    restart: always
    command: ["sqlite_web", "-H", "0.0.0.0", "-x", "/data/chatstorage.db"]
    volumes:
      - ./storages:/data
    ports:
      - "8081:8080"